### PR TITLE
add testing on osx

### PR DESCRIPTION
**Pull request by Autoplectic**
Also remove source testing of 3.4, it's been released for a while.

### CODE REVIEW

**Comment by Autoplectic** [comment]
i'm going to try to see if i can get pypy testing to work too

**Comment by chebee7i** [comment]
Can we squash merge these PRs with lots of "noise" in the commits?  It should help keep the history understandable in logical chunks.  Though I guess that is what a regular merge does too.

**Comment by Autoplectic** [comment]
I'll do so when I get it working

________________________
Ryan G. James
Information Theorist
Complexity Sciences Center
University of California, Davis

**Comment by Autoplectic** [comment]
So this PR now tests pythons 2.7, 3.3, 3.4, 3.5 on linux using conda, it also tests python "nightly" on linux without using conda (all pip installs, etc). Further, it tests python 2.7, 3.5, pypy, and pypy3 on osx.

The two pypys and nightly are "allowed failures". currently, nightly passes without any problems, but is slower because of all the compiling. the pypys fail. numpypy doesn't seem to install on pypy3, so there's that issue. on pypy, things get as far as actually running our tests, but several of them fail for various reasons. it looks like inconsistencies between numpy and numpypy. i'm going to open a new issue to address those.

The pypy situation is an improvement, because before travis wouldn't get far enough to even try running our tests. it would detect that pypy wasn't python 2.7, so it would download the miniconda3 file, and then conda python=pypy would fail a few steps later.

**Pull request merged**
