### PR TITLE
Generalized divergences -- Renyi, Tsallis, Hellinger, and alpha, with many tests

### PR DESCRIPTION
**Pull request by marcharper**
Hi all, I added some popular generalized divergences to dit. Take a look and if you like what you see, please merge it in!

### CODE REVIEW

**Comment by chebee7i** [comment]
Looks great! Thanks @marcharper. Will merge tomorrow if no one else does before then.

**Comment by chebee7i** [comment]
The test failures can be ignored...I just pushed a fix for that.

**Comment by Autoplectic** [comment]
Nice! Looks good to me too, but I'd like to see it rebased on master just so we can have a clean travis check before merging.

**Comment by chebee7i** [comment]
Sure. @marcharper, something like the following should do it:
```
git remote add upstream https://github.com/dit/dit.git
git fetch upstream

git rebase upstream/master
git push -f
```

**Comment by marcharper** [comment]
I added some more tests (for divergence positivity), looks like it all clears just fine.

**Comment by Autoplectic** [comment]
Very nice, thank you Marc! I don't see any reason not to merge now.

**Pull request merged**
